### ISSUE TITLE
DB/table includes/excludes for mysqllvm

### ISSUE THREAD

**Issue by StafDehat** [holland-backup/holland#100]
Feature request:
This is currently possible by manually editing the exclude options passed to tar, but that leaves room for user error.  Also, if the goal is to backup only one database, then that exclude option to [tar] requires a manual adjustment every time a new DB is added to MySQL.  Ideally, I could pass an include argument to holland-mysqllvm, and Holland would programmatically generate a list of files to specifically include in the tar command ($datadir/$db/$table.*, $datadir/ibdata1, $datadir/ib_logfile[01], $datadir/master.info, etc) or alternatively generate an exclude list for tar based on what's not included in the Holland config.

This option should probably come with a commented warning that excluding InnoDB tables has limited benefit based on whether innodb_file_per_table is in use or not.

**Comment by soulen3** [comment]
I'm going to close out this old issue. Please raise a new one if you would still like this feature added to holland.
