### ISSUE TITLE
Add credential test

### ISSUE THREAD

**Issue by StafDehat** [holland-backup/holland#102]
I'd like the abilty to run a command to only verify that holland is able to access the MySQL instance.  "holland bk --dry-run" will do this, but it also does some number crunching that uses system resources and delays the command's return.  I'd like the ability to run something like "holland cred-test" and get output like the following:

<pre>
Authenticate to MySQL.....OK
Perm: SELECT.....OK
Perm: RELOAD.....OK
Perm: SUPER.....OK
Perm: LOCK TABLES.....OK
Perm: REPLICATION CLIENT.....ERROR
Perm: SHOW VIEW.....OK
</pre>

And of course, set exit status appropriately.

**Comment by soulen3** [comment]
The way holland handles dry-runs has changed, and doesn't impact the server like it did in the past. So I think using dry-run is now a valid option instead of adding a credential test. I'm going to go ahead and close this issue.
