### ISSUE TITLE
Deprecate estimating backup sizes

### ISSUE THREAD

**Issue by abg** [holland-backup/holland#104]
I think holland should give up on trying to estimate backup sizes.  It's a hard problem to do this accurately in the face of compression or other transformations and it can be expensive to calculate.  This complicates the code in non-trivial ways in various places as well

I do think some guard to avoid exhausting disk space is important - particularly when backup space is shared with some other critical resource (often the database being backed up).  I think instead of estimation, some basic disk space monitoring should be done.  So rather than aborting if we expect a backup to be too large, holland should rather abort only if disk space falls too low.  This is fairly simple to do with a background thread that just sits in a loop polling statvfs(2) periodically and signaling holland to abort when this falls below some threshold.

I propose three new configuration options to support this with the following tentative naming conventions and default values:

```
[holland:backup]
disk-space-monitor = boolean(default=yes)   # flag to enable/disable monitoring disk space
disk-space-monitor-required-space = filesize(default="5G")  # If the space falls below this threshold, abort
disk-space-monitor-interval = float(default=1.0) # interval in seconds between checks
```

Required space will be compared against available space based on statvfs(2) of the backup directory's mountpoint - the same mechanism holland currently uses to compare estimated space vs. space available.

As far as signaling holland, I think sending a process the signal SIGUSR1 to force and abort makes sense for now.  This works on environments where holland is currently supported.  Holland can install an appropriate signal handler to fail gracefully in this case.

**Comment by soulen3** [comment]
I've gone about solving this a different way.  As of version 1.1.1, Holland will base the size estimate off of the last backup. If there isn't one or the db size has changed by more than a configurable amount, it will use the current size estimator method.  I believe this will be simpler than making Holland multithreaded, but will create fewer false positives during space checks. 

*historic-size** = yes | no

    Defaults to yes. Check for the 'backup.conf' file in the 'newest' spooled folder for the running "backupset".
    If the configuration file exists and contains 'estimated-size' and 'on-disk-size', these values will be used
    to decide if holland has enough free space for a backupset. This means Holland will use values from the previous
    backup to estimate the size of the next backup.

    .. versionadded:: 1.1.1

**historic-size-factor** = #

    Defaults to '1.5'. If the estimated size of the database has changed by more than this multiple, the 'estimated-size-factor' value
    will be used to determine if there is sufficient free space for the backupset.

    .. versionadded:: 1.1.1

**historic-estimated-size-factor** = #

    Defaults to '1.1'. Specifies the scale factor when Holland decides if there is enough
    free space to perform a backup. Holland will throw an error if the system
    has less free space than the last backup size multiplied by this value

.. versionadded:: 1.1.1
