### ISSUE TITLE
holland GTID support

### ISSUE THREAD

**Issue by abg** [holland-backup/holland#108]
Holland LVM plugins are least are lacking support for GTIDs.  mysqldump and xtrabackup should include this by default in most cases, but I haven't tested holland restores with GTIDs in mind.

This should be pretty simple to add.  I would like to support both MariaDB and MySQL 5.6+ GTID implementations.  There should be some good improvements in holland's  LVM support  soon and this can ride on those changes.  This sort of feature will probably be introduced in a major version bump.

**Comment by soulen3** [comment]
I'm going to close out this old issue. Please raise a new one if you would still like this feature added to holland.
