### ISSUE TITLE
"Which Provider To Use When" documentation

### ISSUE THREAD

**Issue by m00dawg** [holland-backup/holland#111]
Andy and I both agreed having a documentation that provides a more scenario-based overview of which provider to use when might prove helpful for users that do not already know which method is the best choice under what scenario.

Might also be a good place to make mention of some edge cases (such as how to backup TokuDB) and gotchas of using various providers.

**Comment by soulen3** [comment]
This request should be moved over to the https://github.com/holland-backup/holland-backup.github.com repo
