### ISSUE TITLE
Documentation - file-per-database

### ISSUE THREAD

**Issue by FancyFane** [holland-backup/holland#117]
When using file-per-database is set to no in the holland config, there is no documentation on how the filename will get saved; all_databases.sql.gz. Can the documentation be updated for this to include this information?

http://docs.hollandbackup.org/provider_configs/mysqldump.html

**Comment by m00dawg** [comment]
I would consider this low hanging fruit but yes the documentation can be easily amended to include this. I'll knock that out at some point soon. That, or you're welcome to give it a go yourself. Just fork the documentation project, make the changes, and send in a PR.

**Comment by m00dawg** [comment]
Created PR 118 with updated documentation which addresses this issue.

**Comment by FancyFane** [comment]
Thank you Tim,

Sorry for the late reply. Once I become more familiar with how git works I
have no problems suggesting changes to the documentation. I apologize for
the delay in this response.

Regards,
Jason

**Comment by m00dawg** [comment]
No worries! Appreciate the suggestion, which has at this point been merged into the main branch. Online documentation may still need to be updated, but the offline versions should appear in the next release of Holland (or you can grab it from git now if you prefer, once you get up to speed with how it works).
