### ISSUE TITLE
[after|before|failed]-backup-command is executed during a dry run

### ISSUE THREAD

**Issue by Komish** [holland-backup/holland#121]
Executing a dry run with after/before/failed-backup-commands being executed causes the scripts to be executed, Given the design of a dry run I'm thinking this is not expected and is likely a bug.

#### Test Environment (If Relevant)

```
# holland --version

Holland Backup v1.0.10
Copyright (c) 2008-2010 Rackspace US, Inc.
More info available at http://hollandbackup.org

[[[[[[[]]]]]]] [[[[[[[]]]]]]]
[[[[[[[]]]]]]]       [[[[[[[]]]]]]]
[[[[[[[]]]]]]] [[[[[[[]]]]]]]
[[[[[[[]]]]]]] [[[[[[[]]]]]]]
```

```
# rpm -qa | grep holland
holland-mysqldump-1.0.10-3.el7.noarch
holland-1.0.10-3.el7.noarch
holland-common-1.0.10-3.el7.noarch
```

```
# cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core)
```
* Also Tested on a CentOS6 Installation

#### Steps to Reproduce
This can probably be reproduced in several ways, but below is the example that has been on my end for completeness. Redirection takes place here, but this also executes a command that does not have output redirected. Given the assumption of a stock configuration:

* Add the 'after-backup-command' to your [holland:backup] section of your backupset:
```
after-backup-command = 'ls > /tmp/file'
```

* Execute a dry run.
```
holland bk --dry-run
```
* Check the redirected file
```
cat /tmp/file
```
This can be fairly harmless, but I'd imagine the case in which a service is recycled, or some configuration-altering script is executed post-backup this could cause a problem when testing with --dry-run.

**Comment by abg** [comment]
Fixed in 1.0.12
