### ISSUE TITLE
Packages for Debian 8 (Jessie)

### ISSUE THREAD

**Issue by kimoi** [holland-backup/holland#123]
hollandbackup.org only provides packages for Debian 7

**Comment by abg** [comment]
I just added the Debian 8 target to [OBS](http://download.opensuse.org/repositories/home:/holland-backup/Debian_8.0/) earlier today, so packages should be available now.  I have not tested them under jessie yet, however.  Please update this issue if you run into any issues.

**Comment by kimoi** [comment]
Installed and is working fine for me so far.

Thanks!
