### ISSUE TITLE
Revert broken SHOW SLAVE STATUS fix for LP#1220841

### ISSUE THREAD

**Issue by mikegriffin** [holland-backup/holland#147]
https://github.com/holland-backup/holland/pull/145

"The fix for LP#1220841 breaks show_slave_status() in the holland mysql client show_slave_status() method. binary is not a valid character set for MySQLdb. This leads to an 'unknown encoding' error and the backup fails.

Without changing connectors to something other than MySQLdb - where 'raw' binary strings can be had easily - I think LP#1220841 is not easily fixed. The original fix for this show slave status bug is reverted here to address the serious defect it introduced in holland 1.0.12."

**Comment by mikegriffin** [comment]
Patch LGTM

I just upgraded a box using mysqldump-lvm from 1.0.12 to 1.0.12-4 and the backup no longer failed. As such, I have voted to push from testing to stable:

https://bodhi.fedoraproject.org/updates/holland-1.0.12-4.el6#comment-396291

**Comment by abg** [comment]
Fixed in commit 89bd61988d729d71b20656534950084aeca1734f which didn't reference this issue.
