### ISSUE TITLE
mysqldump in 1.0.12 forces table locking for transactional databases

### ISSUE THREAD

**Issue by mikegriffin** [holland-backup/holland#148]
Upgrading from holland-mysqldump version 1.0.10 to 1.0.12 changes locking discovery, forcing `--lock-tables` where `--single-transaction` was previously allowed.

Reproduce:

Create a database with no tables and another with a single InnoDB table:

> mysql> show tables from test;
> Empty set (0.00 sec)
> 
> mysql> create database d148;
> Query OK, 1 row affected (0.00 sec)
> 
> mysql> create table d148.t1 (a int) engine=innodb;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> select @@version;
> +-----------+
> | @@version |
> +-----------+
> | 5.0.95    |
> +-----------+
> 1 row in set (0.00 sec)

Holland uses `--single-transaction` for the test database but forces a lock for database d148:

> [root@mg-el5 ~]# holland bk -n
> Holland 1.0.12 started with pid 5343
> --- Starting dry run ---
> Creating backup path /var/spool/holland/default/20160308_223635
> Estimating size of mysqldump backup
> Estimated Backup Size: 570.14KB
> Starting backup[default/20160308_223635] via plugin mysqldump
> Running in dry-run mode.
> Using mysqldump executable: /usr/bin/mysqldump
> mysqldump version 5.0.95
> --events only available for mysqldump 5.1.8+. skipping
> Using mysqldump option --flush-privileges
> Using mysqldump option --routines
> Using mysqldump option --max-allowed-packet=128M
> Using gzip compression level 1 with args
> Wrote backup manifest /var/spool/holland/default/20160308_223635/backup_data/MANIFEST.txt
> Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20160308_223635/my.cnf --flush-privileges --routines --max-allowed-packet=128M --lock-tables d148
> Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20160308_223635/my.cnf --flush-privileges --routines --max-allowed-packet=128M --lock-tables mysql
> Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20160308_223635/my.cnf --flush-privileges --routines --max-allowed-packet=128M --single-transaction test
> Backup completed in 0.06 seconds
> --- Ending dry run ---

Downgrading to Holland 1.0.10 or upgrading to MySQL 5.1 solves the issue:

> [root@mg-el5 ~]# service mysqld stop
> Stopping mysqld:                                           [  OK  ]
> [root@mg-el5 ~]# rpm -e mysql-5.0.95-5.el5_9.i386 mysql-5.0.95-5.el5_9.x86_64 mysql-server-5.0.95-5.el5_9 --nodeps
> warning: /var/log/mysqld.log saved as /var/log/mysqld.log.rpmsave
> 
> [root@mg-el5 ~]# yum install mysql51 mysql51-server
> 
> [root@mg-el5 ~]# holland bk -n
> Holland 1.0.12 started with pid 6143
> --- Starting dry run ---
> Creating backup path /var/spool/holland/default/20160308_224256
> Estimating size of mysqldump backup
> Estimated Backup Size: 570.14KB
> Starting backup[default/20160308_224256] via plugin mysqldump
> Running in dry-run mode.
> Using mysqldump executable: /usr/bin/mysqldump
> mysqldump version 5.1.73
> Using mysqldump option --flush-privileges
> Using mysqldump option --routines
> Using mysqldump option --events
> Using mysqldump option --max-allowed-packet=128M
> Using gzip compression level 1 with args
> Wrote backup manifest /var/spool/holland/default/20160308_224256/backup_data/MANIFEST.txt
> Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20160308_224256/my.cnf --flush-privileges --routines --events --max-allowed-packet=128M --single-transaction d148
> Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20160308_224256/my.cnf --flush-privileges --routines --events --max-allowed-packet=128M --lock-tables mysql
> Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20160308_224256/my.cnf --flush-privileges --routines --events --max-allowed-packet=128M --single-transaction test
> Backup completed in 0.07 seconds
> --- Ending dry run ---

**Comment by abg** [comment]
This is a regression from the fix for https://bugs.launchpad.net/holland-backup/+bug/1081261 that no one caught.  I am currently not testing on MySQL 5.0 as it is EOL.   This support should be entirely dropped at some point.

As far as this bug goes, for "historical reasons" holland uses ```SHOW TABLE STATUS``` with mysql 5.0 (and earlier), and information_schema queries for later versions.  The engine name isn't being canonicalized from the 5.0 path.  This should be a trivial fix.

**Comment by carlwgeorge** [comment]
When you get the fix sorted, I can backport just that fix as a patch to the EPEL5 package, and then we'll stop updating it with new upstream versions.

**Comment by carlwgeorge** [comment]
Holland `1.0.12-5` includes the backported fix.  It has been submitted for EPEL5 testing.

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-7bb56b1744
