### ISSUE TITLE
REQUEST: MongoDB

### ISSUE THREAD

**Issue by jpSimkins** [holland-backup/holland#150]
This is a request to support MongoDB.

I use Holland for mysql already and would really like to use it for MongoDB as the scripts I see out there just do not have what this offers.

**Comment by azlev** [comment]
I made a holland plugin to use mongodump, for now it's just to fit my needs. You can test it and we can talk if it fits your needs too: https://github.com/holland-backup/holland/pull/182

It needs pymongo python package and mongodump.

**Comment by jpSimkins** [comment]
Nice! I will look into this when I have time to get back on that project. For now I am just running a custom script VIA cron but I won't mind checking this out. It'll probably be a few months but I will get to it. Thanks!

**Comment by soulen3** [comment]
#182 has been included in the 1.1.0 release. 

Thanks,
Steve
