### ISSUE TITLE
Package updates for Debian / Ubuntu

### ISSUE THREAD

**Issue by dboune** [holland-backup/holland#152]
Looking around for current packages and not finding. Building them myself OK. Just expressing the desire. Having the PPA updated would be nice too.

Debian 7/8
Ubuntu 14.04 / 16.04

I use Holland on nearly every server I roll out, and I greatly appreciate the work done.

Thank you!

**Comment by kerwin59** [comment]
dboune I created a quick how to for installing holland on Debian 7/8 after finding it failed using Ansible.
Hope you find it useful.
https://github.com/kerwin59/Holland/blob/master/holland-installDebian7_8.txt

**Comment by dboune** [comment]
@kerwin59 Nicely done. You can also automate that process with an Ansible role. Doesn't look like anyone has yet published a role that works with apt.

Closing this now because the current tagged version `v1.0.14` for is available in the openSUSE repositories. This ticket is so old that I was probably referring to `v1.0.12`.

The PPA hasn't been updated in almost 3 years, so guessing that it isn't likely to be revived.
