### ISSUE TITLE
Repo signing key expires this week

### ISSUE THREAD

**Issue by inflatador** [holland-backup/holland#167]
Apologies if you're already aware, but I just noticed that the signing key for the Ubuntu Holland repo ( http://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_14.04/Release.key ) is about to expire:

#apt-key list
pub   1024D/984D0514 2010-07-26 [expires: 2017-03-12]
uid                  home:holland-backup OBS Project <home:holland-backup@build.opensuse.org>

**Comment by abg** [comment]
I offer sincere apologies for the slow response - I had been traveling earlier this week and had some issues logging into github while on the road.

I had extended this OBS key some time ago but, apparently never triggered package rebuilds, so the old key remained.  I am rebuilding now and the updated key should be published shortly.

**Comment by abg** [comment]
This should have been fixed a while ago. Closing
