### ISSUE TITLE
Support SUSE/SLES

### ISSUE THREAD

**Issue by seanorama** [holland-backup/holland#179]
Any plans to support SUSE/SLES?

Is it just a matter of updating the .spec?

**Comment by soulen3** [comment]
I believe this should just be a matter of updating the spec file, but I don't know much about SUSE/SLES packaging.  I've removed the old spec file from this project as it was very outdated. We've been working on one stored on the Fedora build systems: https://src.fedoraproject.org/rpms/holland/blob/master/f/holland.spec

I tried uploading this new SPEC file to build.opensuse.org, but it didn't work
https://build.opensuse.org/package/show/home:holland-backup/holland.rpm

I don't have any plans for this, but would be willing to work with someone on getting packages created
