### ISSUE TITLE
[mariabackup] Left over 'innobackupex' phrases in plugin.util

### ISSUE THREAD

**Issue by troyengel** [holland-backup/holland#190]
While debugging #189 I came across some messaging which wasn't updated after the `innobackupex` plugin source was copied to create `mariabackup`, specifically here:

* https://github.com/holland-backup/holland/blob/master/plugins/holland.backup.mariabackup/holland/backup/mariabackup/util.py#L97

```
    if process.returncode != 0:
        # innobackupex exited with non-zero status
        raise BackupError("innobackupex exited with failure status [%d]" %
                          process.returncode)
```

Just the text itself, user output.

**Comment by soulen3** [comment]
Pending https://github.com/holland-backup/holland/pull/194
