### ISSUE TITLE
[mongodump] Python library 'pymongo' required (setup.py)

### ISSUE THREAD

**Issue by troyengel** [holland-backup/holland#192]
The `mongodump` plugin is making use of the `pymongo` python library, it's not declared in the plugin's setup.py etc. I think this is all that's needed in the `holland.backup.mongodump/setup.py` ?

```
      install_requires=[
         'pymongo'
      ],
```

I confirm pymongo 3.7.0 under python 3.6.6 appears to be functional in basic tests.

(CC: @immanetize / @carlwgeorge for EPEL packaging)

**Comment by carlwgeorge** [comment]
EPEL 6/7 only has pymongo 2.5.2.  If that version is too old then we'll have to skip the mongodump subpackage on EPEL.

**Comment by soulen3** [comment]
Pending https://github.com/holland-backup/holland/pull/194

**Comment by soulen3** [comment]
pymongo 2.5.2 appears to work. There was also an issue with python2 compatibility but I believe that's fixed in https://github.com/holland-backup/holland/pull/194
