### ISSUE TITLE
[pgdump] Set default plugin backupset config to 'user=postgres'

### ISSUE THREAD

**Issue by troyengel** [holland-backup/holland#193]
A PostgreSQL default install only allows the user `postgres` to connect to the database, not even root can connect without becoming the postgres user first (no configs/edit, out of the box). This means an out of the box `holland mk-config pgdump` fails to run, unlike the MySQL defaults.

If we set the default backupset config to `user=postgres` it would provide a similar, out of the box experience for PostgreSQL users which mirrors the MySQL defaults and allow a `holland bk` to work with no edits. This could aide in unit testing as well.

**Comment by soulen3** [comment]
I don't see any issues with defaulting to the 'postgres' user.  
Pending https://github.com/holland-backup/holland/pull/194

**Comment by soulen3** [comment]
My initial testing on this was insufficient.

Before 8323517e664fa81c488f732a6ca9dbfa875129db Holland would attempt to connect to the `root` psql user as the `root` system user .  Now it's trying to connect to the `postgres` psql user as the `root` system user.  This is causing an authentication error in my test environment.  So unless I'm mistaken, there isn't a way to connect to a default PostgreSQL instance other than connecting as the `postgres` system user.

As these configuration options don't seem to buy the user anything, I've removed this from https://github.com/holland-backup/holland/pull/194. I see two options going forward, figure out how to connect as from system `root` user on a default PostgreSQL install. Or have Holland run as `postgres` user.

Please let me know if I'm missing or misunderstand something

**Comment by soulen3** [comment]
Changing the default to the `postgres` user causes an issue with the default psql setup for Ubuntu 16 and 18. 

```
Error while initializing <class 'holland.backup.pgdump.interface.PgDump'> : FATAL:  Peer authentication failed for user "postgres"
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/holland-1.1.1-py3.6.egg/holland/core/backup/base.py", line 72, in load_plugin
   dry_run=dry_run)
 File "/usr/local/lib/python3.6/dist-packages/holland.backup.pgdump-1.1.1-py3.6.egg/holland/backup/pgdump/interface.py", line 68, in __init__
   self.connection = get_connection(self.config)
 File "/usr/local/lib/python3.6/dist-packages/holland.backup.pgdump-1.1.1-py3.6.egg/holland/backup/pgdump/base.py", line 39, in get_connection
   connection = dbapi.connect(database=db, **args)
 File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
   conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "postgres"
```

I'm also concerned with how changing the default will effect existing installations. So I'm leaving the default user at `root` and will mark this issue as closed.

**Comment by evitalis** [comment]
This should not be closed, it is not resolved. The issue on Ubuntu is easily fixed and has nothing to do with the code in Holland. It should still be using the `postgres` user as originally requested.

Changing the default should not affect existing installations as an upgrade will not replace the customized backup set configuration.
