### ISSUE TITLE
Switch bundled third party modules to dependencies

### ISSUE THREAD

**Issue by evitalis** [holland-backup/holland#199]
No third party libraries should be bundled in the application as it is not maintainable nor follows best practices. The only one listed in the README is configobj (https://github.com/DiffSK/configobj).

As a slight aside, any backported standard library modules should also not be copy/pasted to the project. This was an issue in the past and with so many commits doing multiple things its hard to tell if this was already done. Same reasoning as above applies but may also include security issues being fixed in modern versions of these libraries.

**Comment by soulen3** [comment]
I was already working on this with @carlwgeorge.  The bundle version of configobj has been removed from Holland in v1.1.3
https://github.com/holland-backup/holland/releases/tag/v1.1.3

I'll leave this issue open for now as the following questionable files are still bundled.

- https://github.com/holland-backup/holland/blob/master/plugins/holland.backup.mysqldump/holland/backup/mysqldump/mock/mocker.py
- https://github.com/holland-backup/holland/blob/master/plugins/holland.lib.common/holland/lib/safefilename.py
- https://github.com/holland-backup/holland/blob/master/plugins/holland.lib.common/holland/lib/which.py

**Comment by carlwgeorge** [comment]
Don't forget to update the README to remove the configobj mention.  You could also add mentions for those other bundled libraries, or just not include that information in the README at all.

**Comment by soulen3** [comment]
I've updated the README.

Thanks.
