### ISSUE TITLE
'estimate-method=const" for the mysqldump configuration

### ISSUE THREAD

**Issue by soulen3** [holland-backup/holland#213]
1.1.7 related to the use of 'estimate-method=const" for the mysqldump configuration.  This triggers "__init__() takes exactly 2 arguments (1 given)" due to SimpleTableIterator not forwarding the client argument.  This is a patch showing the fix.

https://github.com/holland-backup/holland/blob/master/plugins/holland.lib.mysql/holland/lib/mysql/schema/base.py#L328

--- /home/rack/base.py    2018-10-07 15:39:12.110309348 -0500
+++ /usr/lib/python2.6/site-packages/holland/lib/mysql/schema/base.py    2018-10-07 15:15:06.917095922 -0500
-325,7 +325,7 @@ class SimpleTableIterator(MetadataTableI
         """
         self.client = client
         self.record_engines = record_engines
-        super(SimpleTableIterator, self).__init__()
+        super(SimpleTableIterator, self).__init__(client)
 
     def _faster_mysql51_metadata(self, database):
         sql = ("SELECT TABLE_SCHEMA AS `database`, "

**Comment by sircubbi** [comment]
And the problem is back with 1.1.9 (see commit https://github.com/holland-backup/holland/commit/fcceabb22f87789b393c73ed90a6291ce534d39a#diff-852fae00fcbc66888ad251eecafe4351

**Comment by soulen3** [comment]
Sorry about that. We've added a test in Travis to prevent another regression, and the code passes lint tests.
