### ISSUE TITLE
Hash Sum mismatch in Ubuntu 16.04

### ISSUE THREAD

**Issue by cippaciong** [holland-backup/holland#233]
Hello, I have recently upgraded Ubuntu from 14.04 to 16.04 and have updated the holland repository in `sources.list` accordingly.
When I run `apt-get upgrade` to upgrade holland (I have version `1.0.14-1` installed from Ubuntu 14.04 repo) I get that `Has Sum mismatch` error:
```
The following packages will be upgraded:
  holland
1 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 111 kB of archives.
After this operation, 270 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_16.04 ./ holland 1.1.8-1 [111 kB]
Err:1 https://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_16.04 ./ holland 1.1.8-1
  Hash Sum mismatch
Fetched 4,272 B in 0s (8,478 B/s)
E: Failed to fetch https://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_16.04/./all/holland_1.1.8-1_all.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I tried to remove all the content in `/var/lib/apt/lists/*` but it didn't work.

**Comment by soulen3** [comment]
I wasn't able to reproduce this on a clean install of Ubuntu 16. This appears to be an issue with your local setup rather than a issue with the package repo.  

Can you try downloading the package from a different mirror? https://mirrors.opensuse.org/

**Comment by cippaciong** [comment]
I tried to download the file manually with `curl` both on my laptop (Italy) and on the VPS where I'm trying to update holland (Netherlands) and I get different files :confused: .
https://download.opensuse.org/ should automatically redirect to the closest server, which in the case of the VPS I think is [this one](https://ftp.gwdg.de/pub/opensuse/repositories/home%3A/holland-backup/xUbuntu_16.04/all/holland_1.1.8-1_all.deb). As you can see it returns a 4 KB archive with the following content instead of the `deb` file.
```
drwxr-xr-x root/root         0 2018-10-26 00:20 ./
drwxr-xr-x root/root         0 2018-10-26 00:20 ./etc/
drwxr-xr-x root/root         0 2018-10-26 00:20 ./etc/holland/
drwxr-xr-x root/root         0 2018-10-26 00:20 ./etc/holland/providers/
-rw-r--r-- root/root       188 2018-10-25 23:14 ./etc/holland/providers/README 
-rw-r--r-- root/root      1708 2018-10-25 23:14 ./etc/holland/README
drwxr-xr-x root/root         0 2018-10-26 00:20 ./etc/holland/backupsets/
-rw-r--r-- root/root      1463 2018-10-25 23:14 ./etc/holland/backupsets/default.conf
-rw-r--r-- root/root       890 2018-10-25 23:14 ./etc/holland/holland.conf
drwxr-xr-x root/root         0 2018-10-26 00:20 ./usr/
drwxr-xr-x root/root         0 2018-10-26 00:20 ./usr/share/
drwxr-xr-x root/root         0 2018-10-26 00:20 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-10-26 00:20 ./usr/share/doc/holland/
-rw-r--r-- root/root       138 2018-10-25 23:25 ./usr/share/doc/holland/changelog.Debian.gz
-rw-r--r-- root/root      1680 2018-10-25 23:25 ./usr/share/doc/holland/copyright
```

**Comment by soulen3** [comment]
Looks like the mirror you where using had a older version of the package.  I'm new to Debian packaging and it took me a few iterations to get to something useful.  Hopefully the mirrors have finished syncing, and I'll try to remember to bump the package version number in the future.

**Comment by cippaciong** [comment]
> Hopefully the mirrors have finished syncing

Did they? I'm still getting the wrong file from https://ftp.gwdg.de/pub/opensuse/repositories/home:/holland-backup/xUbuntu_16.04/all/holland_1.1.8-1_all.deb

**Comment by soulen3** [comment]
I've triggered a rebuild in build.opensuse.org. Hopefully that will fix it.
