### ISSUE TITLE
Custom plugin support/documentation

### ISSUE THREAD

**Issue by MatMaciej** [holland-backup/holland#236]
Hi, I've been using Holland 1.0.14 with a modified version of the postgres plugin, which I installed just by running setup.py install. After you've updated Holland version available on your opensuse repo to 1.1.8 and switched to python3 that method stopped working (I've updated the plugin to be compatible with new version). Python3 refuses to detect my plugin and reminder of the holland plugins at the same time, so the real question is this: `Is there a recommended way to create/install custom plugins?` I know that the plugin dir from the holland.conf has been deprecated for quite some time, now installing with setuptools stopped working so how should it be done? I couldn't find anything about that in your documentation.

**Comment by soulen3** [comment]
Running `python3 setup.py install` should install the plugin.  I can't think of any changes that would prevent this from working, assuming your code is compatible with python3.   Are you getting any error messages when you try to install or run the plugin?

**Comment by MatMaciej** [comment]
Everything seems to install correctly, when I try to run the plugin I'm getting `No module named holland.core`, I've verified that I have both `/usr/lib/python3/dist-packages`, where main holland distribution is located after installing it through apt-get, as well as `/usr/local/lib/python3.5/dist-packages` dir, where python installs my plugin, present in path variable for python3 but it seems to only detect the latter. The plugin is pretty much a copy-paste of the postgres plugin with an exclusion list added and I've verified that it's working when I overwrite the default postgres plugin's code so that's my workaround for now. But as keeping it as a custom plugin seemed more future-proof I'd be open to any suggestions as to what could be the cause. If there were no changes that could be the cause since 1.0.14 this can be closed.

**Comment by soulen3** [comment]
I didn't bother packaging the plugins separately for Ubuntu/Debian, so the default pgdump plugin was installed with the new package.   `/usr/lib` is likely before `/usr/local/lib` in python's library path.  So the default one would be picked of before your custom one.  Your fix makes sense, and another option would be to rename your custom plugin.

Ideally we would just get your feature or code into upstream.  So feel free to raise a issue or pull request with the details.
