### ISSUE TITLE
missing python mysqldb module dependency in debian packages 

### ISSUE THREAD

**Issue by johnmenke** [holland-backup/holland#247]
The Debian package for holland is missing a dependency that provides the mysqldb python module, which is required for the myslqdump plugin to function.  This results in an error like the following:

```
root@ellie:/etc/holland/backupsets# holland bk
Holland 1.1.8 started with pid 13813
--- Starting backup run ---
Creating backup path /var/spool/holland/default/20181204_205226
Backup failed: No module named 'MySQLdb'
Released lock /etc/holland/backupsets/default.conf
--- Ending backup run ---
```
This can be fixed with the installation of the python3-mysqldb package,which should be added to the list of depends in the Package definition.

**Comment by soulen3** [comment]
To simplify packaging. I put Holland and it's plugins into a single package.  I didn't want to force the user to install libraries for MySQL, MongoDB, and PostgreSQL, so I didn't include any of them as dependencies.
