### ISSUE TITLE
Refactor xtrabackup and mariabackup plugins to use library MySQL client

### ISSUE THREAD

**Issue by nwbreneman** [holland-backup/holland#249]
The xtrabackup and mariabackup plugins implement their own (essentially duplicate) `mysql.py` MySQL client and `util.py` utility helpers. This functionality should be incorporated into the `lib` plugin instead. Due to an issue with pylint, the `duplicate-code` warning can't be disable inline so linting for these files are disabled entirely.

**Comment by soulen3** [comment]
Updated in version 1.2
