### ISSUE TITLE
Regression in mysqldump plugin MANIFEST.txt backup file names introduced in 1.1.9

### ISSUE THREAD

**Issue by bleve** [holland-backup/holland#260]
I noticed that MANIFEST.txt doesn't any more list full file name for backup.

From new MANIFEST.txt:

mysql	m.sql.gz

1.1.8 still had:

mysql	mysql.sql.gz

**Comment by soulen3** [comment]
Hello,

Thanks for reporting this issue.  I've submitted a fix for this and it will be released in the next version of holland.

```
#holland --version
1.1.11
# cat $(holland bk 2>&1 |grep MANIFEST.txt|awk '{print $NF}')
employee1       employee1.sql.gz
employees       employees.sql.gz
mysql   mysql.sql.gz
test    test.sql.gz
```
