### ISSUE TITLE
support percona xtrabackup 8.0

### ISSUE THREAD

**Issue by mikegriffin** [holland-backup/holland#263]
Submitting on behalf of MZ

Xtrabackup 8.0 has been introduced to be compatible with MySQL 8.0. This version has removed the innobackupex script and now uses the xtrabackup binary exclusively for all functions. The xtrabackup binary requires different options to achieve the same result as innobackupex. Namely, to execute a backup, you need to always start the command with:

/bin/xtrabackup --backup --target=/path/to/datadir [additional options]

Furthermore, you no longer need to append the target path at the end of the command. This means that for Holland-xtrabackup, altering the following in the backupset conf will result in an invalid backup command:

innobackupex = xtrabackup

# holland bk xtrabackup
[...]
Executing: /bin/xtrabackup --defaults-file=/data1/holland_backup/xtrabackup/20190131_195352/my.cnf --stream=xbstream --tmpdir=/data1/holland_backup/xtrabackup/20190131_195352 --no-lock --no-timestamp --parallel=4 /data1/holland_backup/xtrabackup/20190131_195352
  > /data1/holland_backup/xtrabackup/20190131_195352/backup.xb.zst 2 > /data1/holland_backup/xtrabackup/20190131_195352/xtrabackup.log
[...]
    ! xtrabackup: Error: unknown argument: '/data1/holland_backup/xtrabackup/20190131_195352'

A properly arranged command should be along the lines of:

/bin/xtrabackup --backup --target=/data1/mysql8/mysql --stream=xbstream --no-lock --no-timestamp --parallel=4 2> /data1/holland_backup/xtrabackup/20190131_195352/xtrabackup.log | zstd -T8 > /data1/holland_backup/xtrabackup/20190131_195352/backup.xb.zst

**Comment by soulen3** [comment]
Fixed in 1.1.12
