### ISSUE TITLE
Add split option when using inline compression

### ISSUE THREAD

**Issue by mikegriffin** [holland-backup/holland#274]
There are some backup systems that may accelerate copying the backup off of the server when there are multiple files instead of a single eg 1TB file

It might help to have a configuration called split in the compression section:

`[compression]`
`method = pigz`
`inline = yes`
`options = "-p4"`
`level = 1`
`split = 1`

The idea would be to pipe to `split(1)` [GNU coreutils] with a non-configurable (for simplicity) `/usr/bin/split`, with sane defaults.

Assuming the file name would normally be `backup.xb.gz`, I was thinking of using arguments along these lines:

`split -da5 --bytes=1G - backup.xb.gz.`

The expected resulting files would be:

`backup.xb.gz.00000`
`backup.xb.gz.00001`
`backup.xb.gz.00002`
`backup.xb.gz.00003`
`backup.xb.gz.00004`

With `--bytes=1G`, the largest supported backup size (compressed) would be 800TB when `split=1`. We should default to `split=0`

We would expect an error message like "[ERROR] compression option split=1 not supported when inline=0"

Restores could look like:

`cat $(ls backup.xb.gz.* | sort | xargs echo) | pigz -d - | xbstream -x -C extract/`

It would be nice to log an `[INFO]` line with these restore instructions or a `README` in `${backupset}/${backupdir}`

**Comment by mikegriffin** [comment]
If we can trust shell expansion, then this also works for restore:

`pigz -dc - backup.xb.gz.* | xbstream -x -C extract/`

**Comment by mikegriffin** [comment]
After some discussion, relying on bash file globbing behavior:

> Bash scans each word for the characters "*", "?", and "[". If one of these characters appears, then the word is regarded as a PATTERN, and replaced with an alphabetically sorted list of file names matching the pattern.



When `split`=`1` and `split-gigabytes`=`1`, we could use:

`split -a5 --bytes=1G - backup.xb.gz.`


This would also avoid the 800TB limitation by a long shot with these resulting files:

`backup.xb.gz.aaaaa`
`backup.xb.gz.aaaab`
`backup.xb.gz.aaaac`
`backup.xb.gz.aaaad`
`backup.xb.gz.aaaae`

Forcing split size to be gigabytes avoids likely unhelpful very small files due to configuration. It does however seem slightly more confusing when you have a single file like `dbname.sql.gz.aaaaa` and are not expecting split to be enabled.

**Comment by soulen3** [comment]
I was able to pipe the compression output into the split command.  I've hard coded "-a5 --bytes=1G"  as the arguments.  I think these are reasonable defaults, as I'm only expecting this to be used on very large databases.  

https://github.com/holland-backup/holland/blob/a1d591fcce112dbe5b5b99e910fb682d215846de/plugins/holland.lib.common/holland/lib/compression.py?#L137-#L151

```
Wrote backup manifest /var/spool/holland/default/20190213_104332/backup_data/MANIFEST.txt
* Executing: /bin/gzip -1
Splitting dump file
* Executing: /bin/split -a5 --bytes=1G - /var/spool/holland/default/20190213_104332/backup_data/mysql.sql.gz.
Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20190213_104332/my.cnf --flush-privileges --routines --events --max-allowed-packet=128M --lock-tables mysql
* Executing: /bin/gzip -1
Splitting dump file
* Executing: /bin/split -a5 --bytes=1G - /var/spool/holland/default/20190213_104332/backup_data/test.sql.gz.
Executing: /usr/bin/mysqldump --defaults-file=/var/spool/holland/default/20190213_104332/my.cnf --flush-privileges --routines --events --max-allowed-packet=128M --single-transaction test
Debug: Database backups writen to /var/spool/holland/default/20190213_104332/backup_data
```

**Comment by soulen3** [comment]
This was added in 1.1.13, so I'll closing out this issue
