### ISSUE TITLE
Man pages do not exist exist since version 1.1.0

### ISSUE THREAD

**Issue by molaeiali** [holland-backup/holland#275]
Man pages do not exist since version 1.1.0 in releases, why they are removed?

**Comment by soulen3** [comment]
Is it missing from a particular package?

The man page is built from the https://github.com/holland-backup/holland-backup.github.com repo, and instructions for building it are in the INSTALL.md file.

**Comment by molaeiali** [comment]
Ok, i see they are separated, thanks
