### ISSUE TITLE
kill signal not passed to split

### ISSUE THREAD

**Issue by mikegriffin** [holland-backup/holland#285]
In #274 the split option was added to compression. Attempting to kill a holland process, I saw that the compressor (pigz in this case) died, as did holland, but split seems to not have received the signal and had to be killed manually.

**Comment by soulen3** [comment]
I'm not sure what the issue is yet, but I've only been able to reproduce it on Centos 6 using python 2.6.

**Comment by soulen3** [comment]
This is definitely an issue with the subprocess module for python2.6.  There's a subprocess32 module available that fixes this, but it's not packages in EPEL6

**Comment by soulen3** [comment]
This is fixed or disabled in version 1.1.15.  For python 2, if the subprocess32 module is available holland will use that. If it's not available, Holland will disable the split command for python 2.6
