### ISSUE TITLE
yum package for holland-xtrabackup missing depends holland-mysql

### ISSUE THREAD

**Issue by mikegriffin** [holland-backup/holland#286]
Without holland-mysql, we see:

`# holland mc xtrabackup`
`Holland 1.1.13 started with pid 3169`
`Failed to load backup plugin 'xtrabackup': No module named mysql.client.base`

**Comment by soulen3** [comment]
I opened a bug against the package for this.

https://bugzilla.redhat.com/show_bug.cgi?id=1365434
