### ISSUE TITLE
1.1.15 fail to work with python 2.7 because there is no subprocess32 available

### ISSUE THREAD

**Issue by bleve** [holland-backup/holland#288]
System is el7 based, Should be visible on centos7. With following config:

[holland:backup]

plugin = mysqldump
backups-to-keep = 3
failed-backup-command = echo Backup of "${backupset}" failed. | mail -s "holland backup failed on $(hostname)" root

[mysqldump]

file-per-database = yes

So split option is not used. Still running  holland fails:

Holland 1.1.15 started with pid 9550
--- Starting backup run ---
Creating backup path /var/spool/holland/default/20190506_001929
Backup failed: Could not find dependency 'subprocess32'
Released lock /etc/holland/backupsets/default.conf
--- Ending backup run ---

I had impression that only split option was supposed to be not available when subprocess32 is not available. This is not a big dlea, I could fix by installing python2-subprocess32.

**Comment by soulen3** [comment]
This is a problem with the EPEL package and I've let the packager know.

**Comment by immanetize** [comment]
Sorry about that, the next package update should address this.
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-86efa89f98
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-bb53a3db63
