### ISSUE TITLE
Holland fails when saving view definitions containing special characters

### ISSUE THREAD

**Issue by LukeJReid** [holland-backup/holland#297]
Holland Version: 1.1.18
Python: 2.7.5
OS: CentOS 7
MySQL: MariaDB 10.1

When Holland attempts to save a view definition with Fields that contain special characters, it generates an error:

```
[INFO] * Saving view definition for [Redacted tablename]
[WARNING] 'ascii' codec can't encode character u'\xb5' in position 514: ordinal not in range(128)
[ERROR] Backup failed after...
```
In this case, there is a Field that contains the "µ" character. 

This does not appear to be an issue in Holland 1.1.15 as a backup of the same data works correctly on this version.

**Comment by soulen3** [comment]
Hello,

Thanks for reporting this issue. As far as I can tell, nothing has changed with this code between 1.1.15 and 1.1.18 that should be effecting this.

https://github.com/holland-backup/holland/commits/master/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py

This bug only effect systems with an invalid view for a table using a non-default character set.

It has to do with how holland is trying to encode the invalid_views.sql file. So declaring the encoding as uft-16 will 'fix' it.  I don't really like the print statements here, so I'm going to rework this function in the next version of holland.  Current work around would be to drop or update the invalid view.

# git diff
diff --git a/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py b/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
index db474b9..6177eec 100644
--- a/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
+++ b/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py
@@ -457,7 +457,7 @@ def exclude_invalid_views(schema, client, definitions_file):
     """
     LOG.info("* Invalid and excluded views will be saved to %s", definitions_file)
     cursor = client.cursor()
-    with open(definitions_file, "w") as sqlf:
+    with open(definitions_file, "w", encoding="utf-16") as sqlf:
         print("--", file=sqlf)
         print("-- DDL of Invalid Views", file=sqlf)
         print("-- Created automatically by Holland", file=sqlf)
