### ISSUE TITLE
holland-common python2-subprocess32 dependency

### ISSUE THREAD

**Issue by nrhodes91** [holland-backup/holland#303]
I don't know who manages the specfile, however the python2-subprocess32 dependency prevents holland from being installed on Amazon Linux 2 as the python2-subprocess32 package is not present in the repos.

Seeing as the split functionality is disabled if the subprocess32 module is not available, is it necessary to have it as a hard install dependency?

**Comment by soulen3** [comment]
My understanding is that Amazon includes EPEL as one of it's default repos. So it should be able to pull the subprocess32 package from there. Make sure you're using the EL7 version of EPEL and not EL6.

python2 is EOL and I'm hopping to get python3 version rolled out soon. So there probably won't be much traction on this issue.

**Comment by nrhodes91** [comment]
On CentOS7 the package is provided by the base channel, not EPEL. I can't see the package in either EPEL6 or EPEL7.

Thanks, I wasn't sure what the status of the python3 release was; seems I should wait for that.

**Comment by soulen3** [comment]
Ah, I didn't realize subprocess32 was in base.
