### ISSUE TITLE
New debian releases redirect to http url

### ISSUE THREAD

**Issue by sebastianhelbig** [holland-backup/holland#308]
> apt install holland
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  holland
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 97.6 kB of archives.
After this operation, 14.3 kB disk space will be freed.
Err:1 https://download.opensuse.org/repositories/home:/holland-backup/Debian_9.0 ./ holland 1.2.1-0
  Redirection from https to 'http://downloadcontent.opensuse.org/repositories/home:/holland-backup/Debian_9.0/all/holland_1.2.1-0_all.deb' is forbidden
E: Failed to fetch https://download.opensuse.org/repositories/home:/holland-backup/Debian_9.0/./all/holland_1.2.1-0_all.deb  Redirection from https to 'http://downloadcontent.opensuse.org/repositories/home:/holland-backup/Debian_9.0/all/holland_1.2.1-0_all.deb' is forbidden
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by soulen3** [comment]
Thanks for reporting this, but I haven't been able to reproduce this issue.  What version of Debian are you running? 

I did notice while testing that the install instructions for Debian 10 need to be slightly different so I updated https://github.com/holland-backup/holland/blob/master/INSTALL.md

**Comment by sebastianhelbig** [comment]
Thanks for the answer. I had to change the source url from `https`to `http`. Now it is working again.
