### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by Bobspadger** [holland-backup/holland#310]
Hi

Following the instructions to install for ubuntu, and it doesnt look like it has been packed yet (fails at wget 

```
wget https://download.opensuse.org/repositories/home:/holland-backup/x${NAME}_20.04/Release.key
--2020-06-16 14:53:53--  https://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_20.04/Release.key
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-16 14:53:53 ERROR 404: Not Found.
```

I get success if I change to `18.04`

Is this in the pipeline?

**Comment by soulen3** [comment]
I've enabled the new Ubuntu repos on build.opensuse.org.  You should be able to download the packages from the 20.04 repo as soon as it syncs.  The package is the same as the 18.04 version though, so using that package shouldn't cause any problems.
