### ISSUE TITLE
python2-subprocess32 dependency after installing subprocess32 in python2.7 when installing holland-common

### ISSUE THREAD

**Issue by jmjchung** [holland-backup/holland#316]
I am trying to install holland-common and I am continue to getting 

           Error: Package: holland-common-1.1.21-1.el7.noarch (epel)
           Requires: python2-subprocess32
even after I installed subprocess32

Following describes what's installed in my system:

# uname -a
Linux ip-10-118-10-155.us-east-2.compute.internal 4.14.193-149.317.amzn2.x86_64 #1 SMP Thu Sep 3 19:04:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# python --version
Python 2.7.18
# which pip
/usr/bin/pip
# pip --version
pip 9.0.3 from /usr/lib/python2.7/site-packages (python 2.7)
# pip install subprocess32
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already satisfied: subprocess32 in /usr/lib64/python2.7/site-packages
# holland --version
1.1.21
# yum list | grep -i holland
holland.noarch                         1.1.21-1.el7                  @epel
holland-common.noarch                  1.1.21-1.el7                  epel
holland-commvault.noarch               1.1.21-1.el7                  epel
holland-lvm.noarch                     1.1.21-1.el7                  epel
holland-mariabackup.noarch             1.1.21-1.el7                  epel
holland-mongodump.noarch               1.1.21-1.el7                  epel
holland-mysql.noarch                   1.1.21-1.el7                  epel
holland-mysqldump.noarch               1.1.21-1.el7                  epel
holland-mysqllvm.noarch                1.1.21-1.el7                  epel
holland-pgdump.noarch                  1.1.21-1.el7                  epel
holland-xtrabackup.noarch              1.1.21-1.el7                  epel
# yum install holland-common
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                          | 3.7 kB  00:00:00
196 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package holland-common.noarch 0:1.1.21-1.el7 will be installed
--> Processing Dependency: python2-subprocess32 for package: holland-common-1.1.21-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: holland-common-1.1.21-1.el7.noarch (epel)
           Requires: python2-subprocess32
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

What am I missing?

**Comment by soulen3** [comment]
The amazon repos are missing the package. They are included in the base repo for CentOS 7, but not Amazon Linux.

See https://github.com/holland-backup/holland/issues/303

**Comment by jmjchung** [comment]
Are they going to included or in it better off that I install the latest package (version 1.2.x) instead of version 1.1.21?

**Comment by soulen3** [comment]
I don't know who maintains the repo for Amazon Linux. To get the yum install working, you would need to request python2-subprocess32 be added to one of their repos.

There's no python2 version for 1.2. But there's nothing preventing the EL8 version from working on Amazon Linux as long as you have the correct python3 packages installed. I would recommend using that package.
