### ISSUE TITLE
mariabackup 10.5.8 - unknown option '--no-timestamp'

### ISSUE THREAD

**Issue by racker7** [holland-backup/holland#318]
This option needs to be removed for the holland mariadb backups to work on the below versions afaikt.
After commenting it out holland worked.

/usr/lib/python2.7/site-packages/holland/backup/mariabackup/util.py:    args.append("--no-timestamp")

Centos7 3.10.0-1160.2.2.el7.x86_64 x86_64
MariaDB-compat-10.5.8-1.el7.centos.x86_64
MariaDB-server-10.5.8-1.el7.centos.x86_64
MariaDB-backup-10.5.8-1.el7.centos.x86_64
MariaDB-client-10.5.8-1.el7.centos.x86_64
MariaDB-common-10.5.8-1.el7.centos.x86_64
holland-mysql-1.1.21-1.el7.noarch
holland-common-1.1.21-1.el7.noarch
holland-1.1.21-1.el7.noarch
holland-mariabackup-1.1.21-1.el7.noarch
holland-mysqldump-1.1.21-1.el7.noarch

```
~ ]# holland backup xtrabak
Holland 1.1.21 started with pid 4544
--- Starting backup run ---
Creating backup path /var/spool/holland/xtrabak/20201219_164726
* Generating mysql option file: /var/spool/holland/xtrabak/20201219_164726/my.cnf
  + Added !include /root/.my.cnf
  + Added !include /etc/my.cnf
  + Added [client] section with credentials                             from [mysql:client] section
Estimated Backup Size: 128.31MB
Starting backup[xtrabak/20201219_164726] via plugin mariabackup
Executing: /bin/mariabackup --version
/bin/mariabackup based on MariaDB server 10.5.8-MariaDB Linux (x86_64)
Executing: /bin/mariabackup --defaults-file=/var/spool/holland/xtrabak/20201219_164726/my.cnf --backup --stream=xbstream --tmpdir=/var/spool/holland/xtrabak/20201219_164726 --no-timestamp --target-dir=/var/spool/holland/xtrabak/20201219_164726
  > /var/spool/holland/xtrabak/20201219_164726/backup.mb.gz 2 > /var/spool/holland/xtrabak/20201219_164726/mariabackup.log
!! mariabackup  exited with failure status [2]
    ! /bin/mariabackup: unknown option '--no-timestamp'
mariabackup  exited with failure status [2]
Backup failed after 0.08 seconds
auto-purge-failures not enabled. Failed backup not purged.
Backup failed: Failed backup: xtrabak
Released lock /etc/holland/backupsets/xtrabak.conf
--- Ending backup run ---
```
-Melissa E

**Comment by gregherrell** [comment]
I would like to add that the following commit needs done as well.
mariabackup 10.4 has a different return code and holland fails unless this
commit is applied.

https://github.com/holland-backup/holland/pull/312/commits/ccd6c1ce4f902e93153947b5942e12dba87a1628
