### ISSUE TITLE
Mariabackup doesn't use the mariabackup binary

### ISSUE THREAD

**Issue by waypost** [holland-backup/holland#319]
The backup/mariabackup module seems to be a copy of Percona Xtrabackup.  It wants to use the innobackupex script, and doesn't work with the mariabackup binary.

The innobackupex option can be mapped to mariabackup, but even with the --innobackupex flag, the options and syntax are not compatible, and the backup fails.

Unfortunately, versions > MariaDB 10.3 no longer work with this plugin or Xtrabackup, so a fix is urgently needed.

**Comment by soulen3** [comment]
Thanks for reporting this issue. I'll need more information to debug this. What version of Holland are you using?  Can you please share any error messages you're getting? Have any of the default settings for the plugin been changed?

Our CI testing confirms that the mariadbbackup plugin works with MariaDB 10.3, 10.4, and 10.5.
https://travis-ci.org/github/holland-backup/holland

**Comment by waypost** [comment]
I am using MariaDB 10.4 on RHEL 7. I do not have Percona XtraBackup installed.  MariaDB has stated it is incompatible with version 10.3+:

https://mariadb.com/kb/en/percona-xtrabackup-overview/#compatibility-with-mariadb

So, while a backup may seem to complete normally with Percona XtraBackup, you can't count on the reliability of a restore.

The MariaDB documentation says to use "mariabackup --innobackupex" as an alternative.

Here's some errors:

Attempt #1 (Setting innobackupex = mariabackup)

`
Executing: /bin/mariabackup --defaults-file=/var/spool/holland/mariabackup/20210101_230732/my.cnf --backup --stream=xbstream --tmpdir=/var/spool/holland/mariabackup/20210101_230732 --no-timestamp --target-dir=/var/spool/holland/mariabackup/20210101_230732
  > /var/spool/holland/mariabackup/20210101_230732/backup.mb.gz 2 > /var/spool/holland/mariabackup/20210101_230732/mariabackup.log
!! mariabackup  exited with failure status [2]
    ! /bin/mariabackup: unknown option '--no-timestamp'
mariabackup  exited with failure status [2]
Backup failed after 0.77 seconds
`

Attempt #2 (Using a wrapper script to call "mariabackup --innobackupex")

`
Executing: /home/celliott/mariabackup-wrapper.sh --defaults-file=/var/spool/holland/default/20210101_231251/my.cnf --backup --stream=xbstream --tmpdir=/var/spool/holland/default/20210101_231251 --no-timestamp --target-dir=/var/spool/holland/default/20210101_231251
  > /var/spool/holland/default/20210101_231251/backup.mb.gz 2 > /var/spool/holland/default/20210101_231251/mariabackup.log
!! mariabackup  exited with failure status [1]
    ! 210101 23:12:51 innobackupex: Missing argument
mariabackup  exited with failure status [1]
Backup failed after 0.53 seconds
`

This attempt fails because "--target-dir" is not an option.  The target file is actually fed as the second argument. eg:

'
/bin/mariabackup --innobackupex --backup --stream=xbstream --tmpdir=/var/spool/holland/mariabackup/20210101_230732 --no-timestamp /var/spool/holland/mariabackup/20210101_230732
  > /var/spool/holland/mariabackup/20210101_230732/backup.mb.gz 2 > /var/spool/holland/mariabackup/20210101_230732/mariabackup.log
'

This outputs the error:

210101 23:22:06 innobackupex: Error: extra argument found 2

It appears that "mariabackup --innobackupex" doesn't support error output 

I also noticed that the compression directive in my config is being ignored.

Here's a working version of the command that produces the desired compressed output and error log:

`
mariabackup --backup --stream=xbstream 2>/var/spool/holland/default/20210101_133842/mariabackup.log | pigz -1 -p4 > /var/spool/holland/default/20210101_133842/mysql-full.gz
`

Note the "--innobackupex" and "--no-timestamp" flags are unnecessary because the output is a stream being redirected to a specific file.

**Comment by waypost** [comment]
FYI, Rackspace made a minor modification to my local installation this morning to get backups working:

 diff /usr/lib/python2.7/site-packages/holland/backup/mariabackup/util.py /home/rack/210101-01108/mariabackup_util.py_backup
227c227
< #    args.append("--no-timestamp")
---
>     args.append("--no-timestamp")

The removal of "--no-timestamp" allows the backup to function without the addition of "--innobackupex"
