### ISSUE TITLE
[deb packaging] /usr/lib unnecessary copied /debian/holland

### ISSUE THREAD

**Issue by gnanet** [holland-backup/holland#334]
Recently i saw a bunch of holland-backup deployments with a `/debian` folder containing `holland/usr/lib`.
That seemed to be an unnecessary copy, what **normally should go into /usr/lib**.

I inspected the package source tree, and found the debian/holland.install contains on the first line the reference to `debian/holland/usr/lib/`. 

This entry results in a "copy" of usr/lib, because as the build-procedure creates the folders, they are already taken into the package as `usr/lib` so there is no need to re-declare them. 

Removing that first line from `debian/holland.install` results in a clean, well structured .deb package.

**Comment by soulen3** [comment]
Thanks for reporting this issue. 

Can you please let me know what version of the package you're using, and where you sourced it from?

**Comment by gnanet** [comment]
Oh i forgot to write
https://download.opensuse.org/repositories/home:/holland-backup/Debian_10/

The .dsc and the .tar.gz file was the only ones needed.
Version 1.2.5-0

But i see this /debian for at least 3 months on some servers where a partner using holland baclup for mysql

**Comment by soulen3** [comment]
I was able to replicate the issue and confirmed that your fix was correct.  The new packages should be syncing out now.
```
root@2856b64deecb:~# dpkg-query -L holland|grep /debian
root@2856b64deecb:~# holland --version
1.2.5
```

Thanks again!
