### ISSUE TITLE
Allow option for relative path symbolic links

### ISSUE THREAD

**Issue by patakijv** [holland-backup/holland#341]
The ability to create symlinks newest/oldest is nice however there are cases where the links being absolute doesn't work.

1. when the link is created inside a docker container on a volume mounted path, such as a host bind
2. when the entire backup directory is copied to a different location, such as for offsite backup destinations

Perhaps an option for symlinks to be created as relative path could be added or could be one of the possible options for create-symlinks, this would allow it to work relative to the parent directory no matter where it was.

**Comment by soulen3** [comment]
I think I should have time to look at this next week.  Shouldn't be a big deal to add an option for it

**Comment by soulen3** [comment]
Can you please confirm this is what you're after?

```
$ ls -l /var/spool/holland/default/
total 0
drwxrwx---. 3 root root 58 Nov  9 17:24 20211109_172430
drwxrwx---. 3 root root 58 Nov  9 17:24 20211109_172436
drwxrwx---. 3 root root 58 Nov  9 17:24 20211109_172445
lrwxrwxrwx. 1 root root 15 Nov  9 17:24 newest -> 20211109_172445
lrwxrwxrwx. 1 root root 15 Nov  9 17:24 oldest -> 20211109_172430
```

**Comment by patakijv** [comment]
Yep

Sent from my iPhone

On Nov 9, 2021, at 3:26 PM, soulen3 ***@***.***> wrote:

﻿

Can you please confirm this is what you're after?

$ ls -l /var/spool/holland/default/
total 0
drwxrwx---. 3 root root 58 Nov  9 17:24 20211109_172430
drwxrwx---. 3 root root 58 Nov  9 17:24 20211109_172436
drwxrwx---. 3 root root 58 Nov  9 17:24 20211109_172445
lrwxrwxrwx. 1 root root 15 Nov  9 17:24 newest -> 20211109_172445
lrwxrwxrwx. 1 root root 15 Nov  9 17:24 oldest -> 20211109_172430
