### ISSUE TITLE
How to approach multiple mysqldump backupset rentions?

### ISSUE THREAD

**Issue by patakijv** [holland-backup/holland#342]
I have holland setup using a mysqldump backup set.
I would like to have have it run every X hours, and keep X of these (say if every 4 hours I might keep 12 for 2 days).
However I also want to keep one per day (at end of day) and keep, say 14.
Is the way to handle this to: 
- create two nearly identical mysqldump backupsets each with different retention `backups-to-keep` value
- create two different crontab entries explicitly with the backupsets in the crontab entry where one is every 4hrs and the other and end of each day
- the folders will be differently named because they are named with the backupset file name so the different purging rules will only be applied inside the folder for the respective backupset

Is there something I am missing or is there some different way to handle this?
Just need a sanity check or insight into what I have missed in this plan.

**Comment by soulen3** [comment]
That sounds correct.  There's no functionality built into Holland to handle that. So setting up two different backupsets will be your best bet.
