### ISSUE TITLE
xtrabackup failing with invalid option of --no-timestamp

### ISSUE THREAD

**Issue by sumitgarg44** [holland-backup/holland#349]
What is failing?
===========
Noticed holland is not compatible with latest version of xtrabackup 8.0.27. This is because holland adds --no-timestamp option to xtrabackup and latest version prefer to fail backup instead of continue (like previous versions) after throwing a warning.
I didn't find any config override in holland to change this behavior, so probably it needs to fix in code. 

Why?
======
All this is happening because Percona has enabled -strict by default from 8.0.27 to eliminate invalid options as per https://www.percona.com/blog/percona-xtrabackup-changing-to-strict-by-default/ .  

Interim Solution
=============
For the next few releases, Percona will still allow you to change back to the old behavior by passing the parameter –skip-strict, –strict=0, or –strict=OFF

Artifacts
====== 
xtrabackup-8.0.26
xtrabackup version 8.0.26-18 based on MySQL server 8.0.26 Linux (x86_64) (revision id: 4aecf82)
<truncated>.
WARNING: unknown option --no-timestamp
220218 15:10:10 >> log scanned up to (18128244)
 
xtrabackup-8.0.27
xtrabackup version 8.0.27-19 based on MySQL server 8.0.27 Linux (x86_64) (revision id: 50dbc8dadda)
<truncated>
xtrabackup: [ERROR] unknown option '--no-timestamp'.

**Comment by soulen3** [comment]
This should be fixed in 1.2.10
