### ISSUE TITLE
mariabackup fails with more-or-less default parameters

### ISSUE THREAD

**Issue by hexadecagram** [holland-backup/holland#352]
Obviously I'm backing up a remote host. /var/lib/mysql is owned by mysql:mysql with perms 770, and it would seem umask 007. Obviously I'm connecting as root, but I would think that root should have no issue accessing ib_logfile0, nevertheless it tries and fails.

I have attached my holland.conf, backup.conf, and mariabackup.log.

[mariabackup.log](https://github.com/holland-backup/holland/files/8627659/mariabackup.log)
[holland-config.zip](https://github.com/holland-backup/holland/files/8627661/holland-config.zip)

**Comment by soulen3** [comment]
Thanks for reporting this issue. Can you please post the error message and the content of the backup.conf file as text?  I'm not going to open files from an unknow source.
  
The Mariabackup plugin is using the mariabackup command. So it shouldn't need access to the database's filesystem.

**Comment by hexadecagram** [comment]
Sure, no problem. Seems ridiculous that github won't let me post files with a .conf extension, but here we are. I'll just throw a .txt extension on them.

[backup.conf.txt](https://github.com/holland-backup/holland/files/8627905/backup.conf.txt)
[holland.conf.txt](https://github.com/holland-backup/holland/files/8627906/holland.conf.txt)

**Comment by soulen3** [comment]
Sorry I didn't think that though before the first response, and said the wrong thing. Mariabackup is only designed to work locally, and does need access to the filesystem.  So it will always fail on a remote hosts. 

https://jira.mariadb.org/browse/MDEV-15075

I would recommend using the mysqldump plugin to backup remote hosts.

**Comment by hexadecagram** [comment]
Ah, I was not aware.

Might not be a bad idea to be a bit more descriptive about what each backup tool does here: https://docs.hollandbackup.org/docs/overview.html#providers

Anyway thanks for bringing these tools together. I'm looking forward to making use of Holland!
