### ISSUE TITLE
Holland backup to network drive not working

### ISSUE THREAD

**Issue by jknight33** [holland-backup/holland#357]
I am trying to run holland using mariabackup against a network drive.  It will create the mariabackup directory but can't create anything inside this folder and errors off.

error is:
[Errno 13] Permission denied: '/network drive/mariabackup/20230116_074852/my.cnf'

I have met with sys admins on this issue and they can't find any reason why holland can create the directory mariabackup but can't create anything in this directory.
I have tested this to a local directory and all works as expected.  Can holland backup to a network drive?

Any assistance would be greatly appreciated.  Please let me know if you need any additional information

**Comment by soulen3** [comment]
Holland doesn't do anything different for network filesystems.  I'm guessing it's some kind of permission/acl issue. 

In practice, Holland can be fragile when dumping to a non local filesystems. So if possible, you'd probably be better off dumping to the local disk, and copying the dump to the network location. Holland can handle the copy using the `after-backup-command`.

See https://docs.hollandbackup.org/docs/config.html#holland-conf-main-config

**Comment by jknight33** [comment]
Soulen3, 
Thanks for that information.  That helps!
