### ISSUE TITLE
Xtrabackup version 8.0.29-22 based on MySQL server 8.0.29 Plugin: [ERROR] unknown option '--no-timestamp'

### ISSUE THREAD

**Issue by lnogaj** [holland-backup/holland#358]
Getting the subject error when performing command: holland backup xtrabackupfull

I am attaching a file with the complete error.
[Xtrabackup error.txt](https://github.com/holland-backup/holland/files/10452636/Xtrabackup.error.txt)

Reviewing the Xtrabackup Documentation for 8.x reveals there is no option (anymore) called: --no-timestamp

Testing on the command line reveals this:

1.) [root@rhel7-clone holland]# holland backup xtrabackupfull fails with subject error

2.) [root@rhel7-clone bin]# xtrabackup --backup --no-timestamp --datadir=/var/lib/mysql/ --target-dir=/cmysql/backups

The above xtrabackup command reproduces error seen from item 1.)

3.) [root@rhel7-clone bin]# xtrabackup --backup --datadir=/var/lib/mysql/ --target-dir=/cmysql/backups

Backup completed OK!

Please see attached file called Xtrabackup error.txt for complete info.  Hoping to get a fix for this.

[Xtrabackup error.txt](https://github.com/holland-backup/holland/files/10452640/Xtrabackup.error.txt)

**Comment by soulen3** [comment]
Hello,
 You're using the old python2 version of Holland that is no longer supported. Unfortunately, there isn't a packaged python3 version for EL7.  You're best bet is to install Holland from source. They're are instructions at the bottom of this [page](https://github.com/holland-backup/holland/blob/master/INSTALL.md)
