### ISSUE TITLE
All output suppressed when running backup from crontab

### ISSUE THREAD

**Issue by aaronadamsTO** [holland-backup/holland#98]
There seems to be some sort of always-on output suppression going on when crontab runs `holland backup`. I want crontab to email me backup errors, but it doesn't happen.

From console, here are two different `holland` commands that return errors – the first due to an invalid command, the second due to an invalid configuration setting:

```
# holland -l error badcommand
No such command: 'badcommand'
# holland -l error backup
Could not load backupset 'doesnotexist': Config file not found: "/etc/holland/backupsets/doesnotexist.conf".
```

Now let's run them with crontab:

```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
* * * * * root	holland -l error badcommand
* * * * * root	holland -l error backup
#
```

One minute later…

```
New mail has arrived.
# mail
Heirloom mailx version 12.5 6/20/10.  Type ? for help.
"/var/mail/root": 1 message 1 new
>N  1 Cron Daemon        Tue Aug  5 18:56   19/772   Cron <root@greatwhite> holland -l error badcommand
```

The second error should be arriving by mail as well, since it has output; but it's not, which means the command isn't generating any output.

I've tried specifying `-v` but output is still suppressed.

Ideally output suppression should be explicit, and/or an override option should be available.

**Comment by abg** [comment]
Finally fixed in 1.0.12
