### ISSUE TITLE
Job IDs in logs

### ISSUE THREAD

**Issue by StafDehat** [holland-backup/holland#99]
Feature request - Sometimes it takes so long to backup MySQL data that the first backup is still running when the next fires off.  When this happens, the logs become cluttered with multiple start and stop messages in the middle of the log output from the original backup that's still running.  This makes it very difficult to pull all the logs from just that one job that ran for 30 hours.

A solution would be to include a job ID on every log entry in the holland log.  We could then simply grep for that job ID to get all logs relevant to that single run, without all the clutter of other jobs trying to run.

**Comment by soulen3** [comment]
The log format is now configurable in Holland 1.1.0.  This allows the PID to be easily included using the 'format' open under 'logging' in the holland.conf file.

[logging]
format = '%(asctime)s PID-%(process)s [%(levelname)s] %(message)s'

Thanks,
Steve
